travis:
  secure:
    BINSTAR_TOKEN: Ux5PeaufJJ6X53To9ye6jaFDE3F7tvjgjw6+1p0sc2VkcUUMeCBH3/FKHnL+xM74ZqzZcIi/ZHFSRbpaxZNZgV6g02S2NxM+iUBroHzExcSmq9LuVA1E5d3pKEmBUS4CAoNfYb2qXTbCOnreT1Ps+0lOF3YJ4I3Fe6AkFrKACH/DrcuBuDAxIr/ntAuHNdDFOFPHAQxhcNb3DfmmRW2Ab7007uZyOCialDhPRSbcPPz9IUk4KyDiNhQ9Zsh5VwsZ/wl+kZwaMgNgRyRQpLv5+4rLwramlujqiCjwU0YTClP4mQ2O3gPKGQqRY2IykIXCw+s/nia5BcsS2gLYYh/jdFHV64q1TEyL+bZGlacAlA5stW6ICSswaKS8Nm5L4bHRtcEZJc1VmqNB8hRu9/9SKD2Qxucdpwdy4D9O3VttcU8re6xZUQ2JZQJW7eqpjqAOldbXvMcfVWDzxkQX+mVuYnyhfcV5ThAWMZ0eU6ndUuajcgyhjQsmyhNFlMQ1804Sr3P0ehtDR/iUlTA/DaEFfDGz2hmgzE2q1V6IJsaGUcjvWaSkPZF0mEbwWCWmoVr4tXVhPy8y9tydSHZsfYS5luoKw3P+cI+zekCMxYsI+vz5Ur1sr7VIrg654V1aOcRGznR4RHh8bxiBdNC6sQ6iSi4cT4SeFPkHjv7SA8AEptk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
